backend:
  name: github
  repo: Fujitime/porto
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://fuji-halim-rabani.netlify.app"

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: posts/{{slug}}
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: publishedAt, label: Date, widget: date }
      - { name: slug, label: Slug, widget: string }
      - { name: image, label: Image, widget: image, required: false }
      - { label: "Publish", name: "isPublish", widget: "boolean", default: true }
      - { name: body, label: Body, widget: markdown }
